export interface SculptureImage {
  url: string
  alt: string
}

export interface SculptureProject {
  slug: string
  title: string
  years?: string
  description: string
  body: string
  images: SculptureImage[]
  links?: Array<{ label: string; url: string }>
}

export const SCULPTURE_PROJECTS: SculptureProject[] = [
  {
    slug: 'profiler',
    title: 'Profiler',
    years: '1966–',
    description: 'Profilskulpturer i sten och brons — Sivert Lindbloms genomgående serie sedan 1960-talet.',
    body: 'Profilserien är ett av Sivert Lindbloms mest genomgående teman. Skulpturerna är abstraherade mänskliga profiler skurna ur sten eller gjutna i brons. Serien spänner från tidiga verk på 1960-talet till stora offentliga monument.\n\nDe första profilskulpturerna visades på Galerie Burén 1966 och 1968. Senare visades serien på Moderna Museet (Live Show 1974), Lunds konsthall (1993), Bildmuseet Umeå (1993), Galerie Aronowitsch (2005) och VANDALORUM (2016). Profiler finns bland annat på Stockholms universitet (Frescati), Västra skogen T-banestation, Wanås och i ett flertal privata och offentliga samlingar.',
    images: [
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Profiler_0069.jpg', alt: 'Profil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Profiler_0072.jpg', alt: 'Profil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Profiler_0071.jpg', alt: 'Profil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Profiler_0068.jpg', alt: 'Profil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Profiler_0070.jpg', alt: 'Profil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Profiler_0067.jpg', alt: 'Profil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Profiler_0075.jpg', alt: 'Profil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Profiler_0074.jpg', alt: 'Profil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Profiler_0073.jpg', alt: 'Profil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Profiler-stående.jpg', alt: 'Modell; svarvad figur, 1967' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/SAM_7624.jpg', alt: 'Profiler, VANDALORUM 2016. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/20121028_135410.jpg', alt: 'Profiler, Konstakademien 2012. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/20121028_160220.jpg', alt: 'Profiler, Konstakademien 2012. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/SAM_7644.jpg', alt: 'Profiler, VANDALORUM 2016. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/20121028_140224.jpg', alt: 'Profiler 2012. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/20121028_140352.jpg', alt: 'Profiler 2012. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Lunds-konsthall-10.jpg', alt: 'Profiler, Lunds Konsthall 1993' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Lunds-konsthall-7.jpg', alt: 'Profiler, Lunds Konsthall 1993' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Västra-skogen-T.bana_0106.jpg', alt: 'Profil, Västra skogen T-banestation' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Frescati-Profil.jpg', alt: 'Profil, Stockholms Universitet Frescati. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert_Lindblom_Wanas.jpg', alt: 'Profil, Wanås' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Eskilstuna_10.jpg', alt: 'Profil, Eskilstuna' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Eskilstuna_14.jpg', alt: 'Profil, Eskilstuna' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Eskilstuna_21.jpg', alt: 'Profil, Eskilstuna' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Eskilstuna_31.jpg', alt: 'Profil, Eskilstuna' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Eskilstuna_81.jpg', alt: 'Profil, Eskilstuna' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Objekt-Profil-Gotland002-kopia.jpg', alt: 'Profil; Austre, Gotland 2012' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur034-kopia.jpg', alt: 'Profil. Foto: Jan Jansson' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur033a-kopia.jpg', alt: 'Profil. Foto: Jan Jansson' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur029-kopia.jpg', alt: 'Profil. Foto: Jan Jansson' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur043-kopia.jpg', alt: 'Profil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur027-kopia.jpg', alt: 'Profil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur023-kopia.jpg', alt: 'Profil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert396.jpg', alt: 'Profil. Foto: Wilhelm Rapp' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert375.jpg', alt: 'Profil. Foto: Wilhelm Rapp' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/04/Buren-66-1.jpg', alt: 'Galerie Burén, Stockholm 1966' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/04/Buren-66-3.jpg', alt: 'Galerie Burén, Stockholm 1966' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/04/Buren-68-5.jpg', alt: 'Galerie Burén, Stockholm 1968' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Nürnberg2.jpg', alt: 'Nürnberg' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Profil-skiss001.jpg', alt: 'Profilskiss' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/cubegrid001-.jpg', alt: 'Kub; axonometrisk ritning, 1967' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/05/Sivert-1x1-A4.jpg', alt: 'Profiler, kompositionsstudie 1×1' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/05/Sivert-2x2-A4.jpg', alt: 'Profiler, kompositionsstudie 2×2' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/05/Sivert-3x2-liggande-A4.jpg', alt: 'Profiler, kompositionsstudie 3×2' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/05/Sivert-12x4-liggande-A4.jpg', alt: 'Profiler, kompositionsstudie 12×4' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/05/Celsing-12.jpg', alt: 'Profil, Celsingprojekt' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/05/Celsing-5.jpg', alt: 'Profil, Celsingprojekt' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2016/08/SAM_7288.jpg', alt: 'Profiler, VANDALORUM 2016. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2016/08/SAM_7271.jpg', alt: 'Profiler, VANDALORUM 2016. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2016/08/SAM_7256.jpg', alt: 'Profiler, VANDALORUM 2016. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2016/08/SAM_7224.jpg', alt: 'Profiler, VANDALORUM 2016. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2016/08/SAM_7191.jpg', alt: 'Profiler, VANDALORUM 2016. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2016/08/SAM_7097.jpg', alt: 'Profiler, VANDALORUM 2016. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2017/10/20171016_160128.jpg', alt: 'Profil, 2017' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2017/10/20171016_160437.jpg', alt: 'Profil, 2017' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2017/06/20170621_135503.jpg', alt: 'Profil, 2017' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2017/06/20170621_140826.jpg', alt: 'Profil, 2017' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/02/20180227_133414.jpg', alt: 'Profil, 2018' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/02/20180227_132949.jpg', alt: 'Profil, 2018' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/04/SAM_4878-kopia.jpg', alt: 'Profil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/02/SAM_4828.jpg', alt: 'Profil. Foto: Jan Öqvist' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-NK-ljusgård_0091.jpg', alt: 'Profil, NK Ljusgård' },
    ],
  },
  {
    slug: 'metamorfoser',
    title: 'Metamorfoser — Sittare',
    years: '1970–1985',
    description: 'Sittande figurer i sten och brons som förenas i en metamorfosprocess.',
    body: 'Metamorfoser-serien utforskar övergångstillståndet mellan det mänskliga och det abstrakta. De sittande figurerna är gjutna i brons och bearbetade i sten, med en inre rörelse som antyder förvandling och förändring. Skulpturerna har visats bland annat på Lunds konsthall och Moderna Museet.',
    images: [
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur109-kopia.jpg', alt: 'Sittare' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur107-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur105-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur102-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur103-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur117-kopia.jpg', alt: 'Sittare' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur119-kopia.jpg', alt: 'Sittare' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur118-kopia.jpg', alt: 'Sittare' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur121-kopia.jpg', alt: 'Sittare' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur120-kopia.jpg', alt: 'Sittare' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur108-kopia.jpg', alt: 'Sittare' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur101-kopia.jpg', alt: 'Sittare' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur001-kopia.jpg', alt: 'Sittare' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur094-kopia.jpg', alt: 'Sittare. Foto: Sven Åsberg' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur097-kopia.jpg', alt: 'Sittare. Foto: Sven Åsberg' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur059-kopia.jpg', alt: 'Sittare' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur076-kopia.jpg', alt: 'Sittare' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert123-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert143-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert118-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert122-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert125-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert126-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert124-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert121-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert113-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert112-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert108-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert105-kopia.jpg', alt: 'Sittare. Foto: Magnus Lindblom' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/IMG_1334-kopia.jpg', alt: 'Sittare, utomhus' },
    ],
  },
  {
    slug: 'monoliter',
    title: 'Monoliter & Blystoder',
    years: '1975–1982',
    description: 'Monolitiska former i bly och sten, inklusive verken i Paris 1977.',
    body: 'Monoliterna utgör en serie enkla, upprätta former i bly — ett material som ger skulpturerna en specifik tyngd och yta. Verken visades bland annat på Centre Culturel Suédois i Paris 1980 och på Galerie Åsbaek i Köpenhamn 1981.',
    images: [
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bly-klossar012.jpg', alt: 'Azteker; bly 1978' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/bly-klossar004.jpg', alt: 'Azteker; bly 1978' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/bly-klossar007.jpg', alt: 'Azteker; bly 1978' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bly-klossar015.jpg', alt: 'Azteker; bly 1978' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bly-klossar014.jpg', alt: 'Azteker; bly 1978' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Skannad-bild-150260014.jpg', alt: 'Monoliter. Foto: Rolf Berglund' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Skannad-bild-150260013.jpg', alt: 'Monoliter. Foto: Rolf Berglund' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Skannad-bild-150270003.jpg', alt: 'Monoliter. Foto: Rolf Berglund' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Dr-Glas-1.jpg', alt: 'Blystoder, Galleri Doktor Glas' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Dr-Glas-2.jpg', alt: 'Blystoder, Galleri Doktor Glas' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Dr-Glas-3.jpg', alt: 'Blystoder, Galleri Doktor Glas' },
    ],
  },
  {
    slug: 'azteker',
    title: 'Azteker',
    years: '1978–1983',
    description: 'Aztekiskt inspirerade skulpturer med geometrisk komplexitet.',
    body: 'Aztekerna är en serie skulpturer inspirerade av prekolumbiansk konst och arkitektur. De karakteristiska trappstegsmönstren och den geometriska upprepningen ger skulpturerna ett monumentalt uttryck trots ofta liten skala. Serien utforskar hur förhistoriska formmönster kan transformeras till ett modernt skulpturalt språk.\n\nVisades bl.a. på Galleri Doktor Glas, Kungsträdgården, Stockholm 1978 och dokumenterades i Kalejdoskop Nr 1/78.',
    images: [
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Azteker-1.jpg', alt: 'Aztek skulptur 1' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Azteker-2.jpg', alt: 'Aztek skulptur 2' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Azteker-3.jpg', alt: 'Aztek skulptur 3' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bly-klossar012.jpg', alt: 'Azteker; bly 1978' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/bly-klossar004.jpg', alt: 'Azteker; bly 1978' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/bly-klossar007.jpg', alt: 'Azteker; bly 1978' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bly-klossar015.jpg', alt: 'Azteker; bly 1978' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bly-klossar014.jpg', alt: 'Azteker; bly 1978' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Skannad-bild-150610027.jpg', alt: 'Kalejdoskop Nr 1/78' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Skannad-bild-150610028.jpg', alt: 'Kalejdoskop Nr 1/78' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Skannad-bild-150610029.jpg', alt: 'Kalejdoskop Nr 1/78' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Skannad-bild-150610030.jpg', alt: 'Kalejdoskop Nr 1/78' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Skannad-bild-150610031.jpg', alt: 'Kalejdoskop Nr 1/78' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Skannad-bild-150610032.jpg', alt: 'Kalejdoskop Nr 1/78' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Skannad-bild-150610033.jpg', alt: 'Kalejdoskop Nr 1/78' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Skannad-bild-150610034.jpg', alt: 'Kalejdoskop Nr 1/78' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Skannad-bild-150610035.jpg', alt: 'Kalejdoskop Nr 1/78' },
    ],
  },
  {
    slug: 'tidiga-skulpturer',
    title: 'Tidiga skulpturer',
    years: '1955–1968',
    description: 'Verk från 1950- och 1960-talen som spänner från figurativt till abstrakt.',
    body: 'De tidiga skulpturerna visar Sivert Lindbloms väg från figurativ konst mot ett alltmer abstrakt formspråk. Bland de tidiga verken finns "Utan titel" (brons, 100 cm, 1959), "Nike II" (brons, 100 cm, 1960), "Självbild" (1961, 1963) och "Fritt efter Rodin" (1961). Under 1950-talet arbetade han nära arkitekturen, bland annat i samarbete med Peter Celsing. 1960-talets verk, tillkomna delvis under åren i Locarno (1963–1966), visar ett allt friare förhållande till formen.',
    images: [
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert678-kopia.jpg', alt: 'Tidigt verk' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert050-kopia.jpg', alt: 'Tidigt verk' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert060-kopia.jpg', alt: 'Tidigt verk' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert054-kopia.jpg', alt: 'Tidigt verk' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert065-kopia.jpg', alt: 'Tidigt verk' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert071-kopia.jpg', alt: 'Tidigt verk' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert072-kopia.jpg', alt: 'Tidigt verk' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert056-kopia.jpg', alt: 'Tidigt verk' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert058-kopia.jpg', alt: 'Tidigt verk' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert629-kopia1.jpg', alt: 'Tidigt verk' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert628-kopia1.jpg', alt: 'Tidigt verk' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Aronow.Mattias04670-kopia-2.jpg', alt: 'Tidigt verk, foto: Mattias Aronow' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/SAM_7585.jpg', alt: 'Tidiga skulpturer, installationsvy' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/SAM_7586.jpg', alt: 'Tidiga skulpturer, installationsvy' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/20121028_135633.jpg', alt: 'Tidiga skulpturer, utställning 2012' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/20121028_135512.jpg', alt: 'Tidiga skulpturer, utställning 2012' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Sivert-Lindblom-Mariestad-1962.jpg', alt: 'Mariestad 1962' },
    ],
  },
  {
    slug: 'kofeser',
    title: 'Kofeser — meningslös meningsfullhet',
    years: '1980–1990',
    description: 'En serie skulpturer som undersöker meningslös meningsfullhet.',
    body: 'Kofeser är ett ord utan definition — en kofes kan vara vad som helst. Serien uppkom spontant, ur slumpen och omedvetna skapande ögonblick, jämförbart med improviserad jazz. Serien utforskar gränsen mellan objekt och skulptur, mellan det vardagliga och det konstnärliga. Birger Vikström har skrivit om vad en kofes egentligen är i "13 berättelser".',
    links: [
      { label: 'Birger Vikström — "Vad är en kofes?" ur 13 berättelser', url: 'https://sivertlindblom.se/texter/andras-texter/kofes-vad-ar-en-kofes-las-birger-vikstroms-berattelse-om-en-kofes-ur-hans-13-berattelser/' },
    ],
    images: [
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/DSC01868-kopia.jpg', alt: 'Kofes' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Kofeser-.jpg', alt: 'Kofeser' },
    ],
  },
  {
    slug: 'blyplattor',
    title: 'Blyplattor',
    years: '1975–1982',
    description: 'Reliefverk i bly med subtila ytbehandlingar.',
    body: 'Blyplattorna är platta, reliefliknande verk som utnyttjar blyets mjukhet och mörkhet. År 1978 undersökte Sivert Lindblom två ytstrukturer inom ett definierat geometriskt ramverk — samma yta i olika format. Verken består av "blybeklädda plattor inom en tydligt definierad svartmålad ram", där varje platta bär en signatur med "exakt kvadratdecimetermåttet av det inre fältet". Dessa blyplattor ställdes ut på Doktor Glas i Kungsträdgården 1978 för första gången.',
    images: [
      { url: 'https://media.sivertlindblom.se/2015/03/Blyplatta-150620028-.jpg', alt: 'Blyplatta' },
      { url: 'https://media.sivertlindblom.se/2015/03/Blyplatta-150620026-.jpg', alt: 'Blyplatta' },
      { url: 'https://media.sivertlindblom.se/2015/03/Blyplatta-150620030-.jpg', alt: 'Blyplatta' },
      { url: 'https://media.sivertlindblom.se/2015/03/Blyplatta-150620029-.jpg', alt: 'Blyplatta' },
      { url: 'https://media.sivertlindblom.se/2015/03/Blyplatta-150620027-.jpg', alt: 'Blyplatta' },
      { url: 'https://media.sivertlindblom.se/2015/03/Blyplatta-150620025-.jpg', alt: 'Blyplatta' },
      { url: 'https://media.sivertlindblom.se/2015/03/Blyplatta-150620024-.jpg', alt: 'Blyplatta' },
      { url: 'https://media.sivertlindblom.se/2015/03/Blyplatta-150620023-.jpg', alt: 'Blyplatta' },
    ],
  },
  {
    slug: 'tradkonstruktioner',
    title: 'Trädkonstruktioner',
    years: '1974–1978',
    description: 'Skulpturer och konstruktioner i trä, bl.a. från Live Show II i Luzern.',
    body: 'Trädkonstruktionerna visar Lindbloms undersökning av organiska material och konstruktionsprinciper. Flera av verken skapades för Live Show II på Kunstmuseum Luzern 1977, i samarbete med Björn Lövin och Ulrik Samuelson.',
    images: [
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/LuzernTräd022.jpg', alt: 'Trädkonstruktion, Luzern' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/LuzernTräd021.jpg', alt: 'Trädkonstruktion, Luzern' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/LuzernTräd020.jpg', alt: 'Trädkonstruktion, Luzern' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/LuzernTräd019.jpg', alt: 'Trädkonstruktion, Luzern' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/LuzernTräd018.jpg', alt: 'Trädkonstruktion, Luzern' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/LuzernTräd017.jpg', alt: 'Trädkonstruktion, Luzern' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/LuzernTräd013.jpg', alt: 'Trädkonstruktion, Luzern' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/LuzernTräd011.jpg', alt: 'Trädkonstruktion, Luzern' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/LuzernTräd010.jpg', alt: 'Trädkonstruktion, Luzern' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/LuzernTräd008.jpg', alt: 'Trädkonstruktion, Luzern' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Lindblom-Live-Show-Luzern-0481.jpg', alt: 'Live Show II, Luzern 1977' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur055-kopia.jpg', alt: 'Trädkonstruktion' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Bok-Skulptur051-kopia.jpg', alt: 'Trädkonstruktion' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Aronowitsch-1.jpg', alt: 'Trädkonstruktion, foto Aronowitsch' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/sivert_lindblom-2.jpg', alt: 'Trädkonstruktion' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/20120730_131452.jpg', alt: 'Trädkonstruktion, 2012' },
    ],
  },
  {
    slug: 'tornmodeller',
    title: 'Tornmodeller',
    years: '1985–1995',
    description: 'Modeller och tävlingsförslag för torn och höga strukturer.',
    body: 'Tornmodellerna är en serie studier och tävlingsförslag för monumentala vertikala strukturer. Tornet representerar det stigande i förhållande till sin omgivning — en metafor för konstruktion i vid bemärkelse, med rötter i klassiska arkitekturprinciper om bas, mittparti och krön. De kombinerar skulpturens formspråk med arkitekturens skala och funktion.',
    images: [
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Sivert-Lindblom-Torn-A1-.jpg', alt: 'Tornmodell A1' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Sivert-Lindblom-Torn-A2-.jpg', alt: 'Tornmodell A2' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Sivert-Lindblom-Torn-B1-.jpg', alt: 'Tornmodell B1' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Sivert-Lindblom-Torn-B2-.jpg', alt: 'Tornmodell B2' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Sivert-Lindblom-Torn-C-.jpg', alt: 'Tornmodell C' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Sivert-Lindblom-Torn-D-.jpg', alt: 'Tornmodell D' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/03/Sivert-Lindblom-Torn-E.jpg', alt: 'Tornmodell E' },
    ],
  },
  {
    slug: 'arbetsmodeller',
    title: 'Arbetsmodeller',
    years: '1960–2000',
    description: 'Arbetsmodeller i gips, lera och trä som dokumenterar skulpturprocessen.',
    body: 'Arbetsmodellerna ger en inblick i Sivert Lindbloms kreativa process. Dessa skalmodeller — i gips, lera, trä och plast — utgör en bro mellan idé och slutfört verk. Många av de offentliga skulpturerna föregicks av noggranna modellstudier.',
    images: [],
  },
  {
    slug: 'grafik',
    title: 'Grafik i urval',
    years: '1966–2018',
    description: 'Teckningar, grafikblad och studier som dokumenterar det konstnärliga arbetet.',
    body: 'Grafiken utgör ett komplement till skulpturarbetet — teckningar, studier och grafikblad som visar det konstnärliga tänkandets rörelser. Bland de tidiga bladen finns profilstudier, axonometriska skisser och geometriska kompositioner från 1960-talet. Senare tillkom digitala kompositioner med variationer av rutnät och strukturer (2018).',
    images: [
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Linje-profil002.jpg', alt: 'Linjeprofil' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Skrynkligneg001.jpg', alt: 'Skrynklig, negativ' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/SkrynkligDubbel003.jpg', alt: 'Skrynklig dubbel' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-Profil004BWprint.jpg', alt: 'Profil, svartvitt' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/SkrynkligProfilPersp.002.jpg', alt: 'Skrynklig profil, perspektiv' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/triple001.jpg', alt: 'Triple' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Profil-skiss001.jpg', alt: 'Profilskiss' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-trassel002.jpg', alt: 'Trassel 2' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Sivert-trassel001.jpg', alt: 'Trassel 1' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/Komplicerad-kub001.jpg', alt: 'Komplicerad kub' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2015/01/cubegrid001-.jpg', alt: 'Kubgrid' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/05/Sivert-1x1-A4.jpg', alt: '1×1 komposition' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/05/Sivert-1111-mindre-liggande-A4.jpg', alt: '1111 komposition' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/05/Sivert-2x2-A4.jpg', alt: '2×2 komposition' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/05/Sivert-3x2-liggande-A4.jpg', alt: '3×2 komposition' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/05/Sivert-4x2-liggande-A4.jpg', alt: '4×2 komposition' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/05/Sivert-9x7-A4.jpg', alt: '9×7 komposition' },
      { url: 'https://sivertlindblom.se/wp-content/uploads/2018/05/Sivert-12x4-liggande-A4.jpg', alt: '12×4 komposition' },
    ],
  },
]
