export interface SculptureLocation {
  id: string
  title: string
  year: number
  city: string
  country: string
  lat: number
  lng: number
  type: 'exterior' | 'interior' | 'metro'
  slug?: string
  description?: string
}

export const SCULPTURE_LOCATIONS: SculptureLocation[] = [
  // Stockholm exteriors
  {
    id: 'blasieholmstorg-1989',
    title: 'Blasieholmstorg — Hästar i brons',
    year: 1989,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3295,
    lng: 18.0771,
    type: 'exterior',
    slug: 'blasieholmstorg-1989',
    description: 'Två grönpatinerade bronshästar inspirerade av San Marcoshästarna i Venedig.',
  },
  {
    id: 'sergels-torg-1998',
    title: 'Sergels torg — Sergel monumentet',
    year: 1998,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3324,
    lng: 18.0633,
    type: 'exterior',
    description: 'Monument på Sergels torg, centrala Stockholm.',
  },
  {
    id: 'kungliga-biblioteket-1998',
    title: 'Kungliga Biblioteket',
    year: 1998,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3349,
    lng: 18.0784,
    type: 'exterior',
    description: 'Skulptur vid Kungliga Bibliotekets fasad, Humlegården.',
  },
  {
    id: 'synagogan-1998',
    title: 'Synagoga — Förintelsenmonumentet',
    year: 1998,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3368,
    lng: 18.0656,
    type: 'exterior',
    description: 'Minnesmärke för Förintelsen vid Stockholms synagoga.',
  },
  {
    id: 'frescati-1987',
    title: 'Stockholms Universitet Campus',
    year: 1987,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3656,
    lng: 18.0554,
    type: 'exterior',
    slug: 'frescati-1987',
    description: 'Skulpturer på Stockholms Universitets campus i Frescati.',
  },
  {
    id: 'sas-huvudkontor-1988',
    title: 'SAS Huvudkontor, Frösundavik',
    year: 1988,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3808,
    lng: 18.0105,
    type: 'exterior',
    description: 'Utomhusskulptur vid SAS huvudkontor i Frösundavik.',
  },
  {
    id: 'haga-norra-1993',
    title: 'Haga Norra gångbro',
    year: 1993,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3547,
    lng: 18.0157,
    type: 'exterior',
    description: 'Skulptur på gångbro vid Haga Norra.',
  },
  {
    id: 'seb-banken-1992',
    title: 'SEB Banken Huvudkontor',
    year: 1992,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3797,
    lng: 17.9281,
    type: 'exterior',
    description: 'Skulptur vid SEB:s huvudkontor i Rissne.',
  },
  {
    id: 'kungstradgarden-1997',
    title: 'Kungsträdgården, norra delen',
    year: 1997,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3326,
    lng: 18.0719,
    type: 'exterior',
    description: 'Skulptur i Kungsträdgårdens norra del.',
  },
  {
    id: 'fersenska-palatset-1975',
    title: 'Fersenska Palatset, Handelsbanken',
    year: 1975,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3315,
    lng: 18.0649,
    type: 'exterior',
    description: 'Skulptur vid Fersenska Palatset på Blasieholmen.',
  },
  {
    id: 'garnisonen-1972',
    title: 'Garnisonen',
    year: 1972,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3354,
    lng: 18.0957,
    type: 'exterior',
    description: 'Skulptur vid Garnisonen på Östermalm.',
  },

  // Stockholm interiors
  {
    id: 'vastra-skogen-1975',
    title: 'Västra skogen T-banestation',
    year: 1975,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3501,
    lng: 17.9866,
    type: 'metro',
    slug: 'vastra-skogen-1975',
    description: 'Konstverk i Västra skogens tunnelbanestation på den gröna linjen.',
  },
  {
    id: 'riksbanken-1973',
    title: 'Sveriges Riksbank',
    year: 1973,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3270,
    lng: 18.0694,
    type: 'interior',
    description: 'Konstverk i Sveriges Riksbanks interiör.',
  },
  {
    id: 'medborgarplatsen-1984',
    title: 'Riksbyggen/Göta Ark, Medborgarplatsen',
    year: 1984,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3144,
    lng: 18.0721,
    type: 'interior',
    description: 'Konstverk i Riksbyggens kontorshus vid Medborgarplatsen.',
  },
  {
    id: 'stadsteatern-1970',
    title: 'Stadsteatern Stockholm',
    year: 1970,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3124,
    lng: 18.0728,
    type: 'interior',
    description: 'Konstverk i Stockholms Stadsteaters interiör.',
  },
  {
    id: 'nk-ljusgard-1968',
    title: 'NK Ljusgård',
    year: 1968,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3329,
    lng: 18.0650,
    type: 'interior',
    description: 'Konstverk i NK:s ljusgård på Hamngatan.',
  },
  {
    id: 'berns-1991',
    title: 'Berns Ljusgård',
    year: 1991,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3327,
    lng: 18.0740,
    type: 'interior',
    description: 'Konstverk i Berns salongers ljusgård.',
  },

  // Malmö
  {
    id: 'gustav-adolfs-torg-2002',
    title: 'Gustav Adolfs torg, fontäner',
    year: 2002,
    city: 'Malmö',
    country: 'Sweden',
    lat: 55.6053,
    lng: 13.0023,
    type: 'exterior',
    slug: 'gustav-adolfs-torg-2002',
    description: 'Fontäner på Gustav Adolfs torg i centrala Malmö.',
  },
  {
    id: 'potatisackern-2001',
    title: 'Potatisåkern — Profilen',
    year: 2001,
    city: 'Malmö',
    country: 'Sweden',
    lat: 55.5954,
    lng: 12.9999,
    type: 'exterior',
    description: 'Profilskulptur i Potatisåkerns park, Malmö.',
  },
  {
    id: 'skissernas-museum-1988',
    title: 'Skissernas Museum, fasad',
    year: 1988,
    city: 'Lund',
    country: 'Sweden',
    lat: 55.7059,
    lng: 13.1881,
    type: 'exterior',
    description: 'Skulptur på Skissernas Museums fasad i Lund.',
  },

  // New York
  {
    id: 'nobelmonument-2003',
    title: 'Nobelmonument',
    year: 2003,
    city: 'New York',
    country: 'USA',
    lat: 40.7128,
    lng: -74.0060,
    type: 'exterior',
    slug: 'nobelmonument-new-york-2003',
    description: 'Nobelmonument i New York, USA.',
  },

  // Tokyo
  {
    id: 'ambassad-tokyo-1990',
    title: 'Sveriges ambassad, entré',
    year: 1990,
    city: 'Tokyo',
    country: 'Japan',
    lat: 35.6521,
    lng: 139.7437,
    type: 'exterior',
    description: 'Entréskulptur vid Sveriges ambassad i Tokyo.',
  },

  // Other Swedish cities
  {
    id: 'eskilstuna-2002',
    title: 'Eskilstuna rondellen — Profilen',
    year: 2002,
    city: 'Eskilstuna',
    country: 'Sweden',
    lat: 59.3666,
    lng: 16.5077,
    type: 'exterior',
    description: 'Profilskulptur i rondell i centrala Eskilstuna.',
  },
  {
    id: 'baltessspannarparken-2013',
    title: 'Bältesspännarparken',
    year: 2013,
    city: 'Göteborg',
    country: 'Sweden',
    lat: 57.6990,
    lng: 11.9786,
    type: 'exterior',
    description: 'Skulptur i Bältesspännarparken, Göteborg.',
  },
  {
    id: 'skövde-1995',
    title: 'Cavallobrunnen, Resecentrum',
    year: 1995,
    city: 'Skövde',
    country: 'Sweden',
    lat: 58.3908,
    lng: 13.8458,
    type: 'exterior',
    description: 'Cavallo-brunn vid Resecentrum i Skövde.',
  },
  {
    id: 'nobel-forum-1993',
    title: 'Nobel Forum',
    year: 1993,
    city: 'Solna',
    country: 'Sweden',
    lat: 59.3622,
    lng: 18.0241,
    type: 'interior',
    description: 'Konstverk i Nobel Forum i Solna.',
  },
  {
    id: 'pharmacia-1984',
    title: 'Pharmacia entréplats',
    year: 1984,
    city: 'Uppsala',
    country: 'Sweden',
    lat: 59.8459,
    lng: 17.6310,
    type: 'exterior',
    description: 'Konstverk vid Pharmacias entré i Uppsala.',
  },
  {
    id: 'gu-biblioteket-1985',
    title: 'Göteborgs Universitetsbibliotek',
    year: 1985,
    city: 'Göteborg',
    country: 'Sweden',
    lat: 57.6893,
    lng: 11.9797,
    type: 'interior',
    description: 'Konstverk i Göteborgs Universitetsbibliotek.',
  },
  {
    id: 'tetra-pak-1984',
    title: 'Tetra Pak',
    year: 1984,
    city: 'Lausanne',
    country: 'Switzerland',
    lat: 46.5197,
    lng: 6.6323,
    type: 'interior',
    description: 'Konstverk i Tetra Paks huvudkontor i Lausanne.',
  },
  {
    id: 'roslagens-sparbank-2004',
    title: 'Roslagens Sparbank',
    year: 2004,
    city: 'Norrtälje',
    country: 'Sweden',
    lat: 59.7580,
    lng: 18.7042,
    type: 'exterior',
    description: 'Skulptur vid Roslagens Sparbank i Norrtälje.',
  },
  {
    id: 'uppsala-stadsbibliotek-1986',
    title: 'Uppsala Stadsbibliotek',
    year: 1986,
    city: 'Uppsala',
    country: 'Sweden',
    lat: 59.8592,
    lng: 17.6375,
    type: 'interior',
    description: 'Konstverk i Uppsala Stadsbibliotek.',
  },
  {
    id: 'vallingby-backe-1966',
    title: 'Vällingby backe',
    year: 1966,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3625,
    lng: 17.8724,
    type: 'exterior',
    description: 'Skulptur vid Vällingby backe i västra Stockholm.',
  },
  {
    id: 'dagens-nyheter-1965',
    title: 'Bronsgaller, Dagens Nyheter',
    year: 1965,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3280,
    lng: 18.0148,
    type: 'exterior',
    description: 'Bronsgaller vid Dagens Nyheters redaktion, Marieberg.',
  },
]
