export interface SculptureLocation {
  id: string
  title: string
  year: number
  city: string
  country: string
  lat: number
  lng: number
  type: 'exterior' | 'interior' | 'metro'
  slug?: string
  description?: string
}

export const SCULPTURE_LOCATIONS: SculptureLocation[] = [
  // ── Stockholm exteriors ─────────────────────────────────────
  {
    id: 'blasieholmstorg-1989',
    title: 'Blasieholmstorg — Hästar i brons',
    year: 1989,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3308,
    lng: 18.0757,
    type: 'exterior',
    slug: 'blasieholmstorg-1989',
    description: 'Två grönpatinerade bronshästar inspirerade av San Marcoshästarna i Venedig.',
  },
  {
    id: 'sergels-torg-1998',
    title: 'Sergels torg — Sergel monumentet',
    year: 1998,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3326,
    lng: 18.0635,
    type: 'exterior',
    description: 'Monument på Sergels torg, centrala Stockholm.',
  },
  {
    id: 'kungliga-biblioteket-1998',
    title: 'Kungliga Biblioteket',
    year: 1998,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3382,
    lng: 18.0721,
    type: 'exterior',
    description: 'Skulptur vid Kungliga Bibliotekets fasad, Humlegården.',
  },
  {
    id: 'synagogan-1998',
    title: 'Synagoga — Förintelsenmonumentet',
    year: 1998,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3319,
    lng: 18.0743,
    type: 'exterior',
    description: 'Minnesmärke för Förintelsen vid Stockholms synagoga, Wahrendorffsgatan.',
  },
  {
    id: 'frescati-1987',
    title: 'Stockholms Universitet Campus',
    year: 1987,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3658,
    lng: 18.0550,
    type: 'exterior',
    slug: 'frescati-1987',
    description: 'Skulpturer på Stockholms Universitets campus i Frescati.',
  },
  {
    id: 'sas-huvudkontor-1988',
    title: 'SAS Huvudkontor, Frösundavik',
    year: 1988,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3717,
    lng: 18.0239,
    type: 'exterior',
    description: 'Utomhusskulptur vid SAS huvudkontor i Frösundavik, Solna.',
  },
  {
    id: 'haga-norra-1993',
    title: 'Haga Norra gångbro',
    year: 1993,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3630,
    lng: 18.0226,
    type: 'exterior',
    description: 'Skulptur på gångbro vid Haga Norra, Solna.',
  },
  {
    id: 'seb-banken-1992',
    title: 'SEB Banken Huvudkontor',
    year: 1992,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3686,
    lng: 17.9713,
    type: 'exterior',
    description: 'Skulptur vid SEB:s huvudkontor i Rissne, Sundbyberg.',
  },
  {
    id: 'kungstradgarden-1997',
    title: 'Kungsträdgården, norra delen',
    year: 1997,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3270,
    lng: 18.0695,
    type: 'exterior',
    description: 'Skulptur i Kungsträdgårdens norra del.',
  },
  {
    id: 'fersenska-palatset-1975',
    title: 'Fersenska Palatset, Handelsbanken',
    year: 1975,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3285,
    lng: 18.0782,
    type: 'exterior',
    description: 'Skulptur vid Fersenska Palatset på Blasieholmen.',
  },
  {
    id: 'garnisonen-1972',
    title: 'Garnisonen',
    year: 1972,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3361,
    lng: 18.0963,
    type: 'exterior',
    description: 'Skulptur vid Garnisonen på Östermalm, Karlavägen 100.',
  },

  // ── Stockholm interiors / tunnelbana ────────────────────────
  {
    id: 'vastra-skogen-1975',
    title: 'Västra skogen T-banestation',
    year: 1975,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3418,
    lng: 18.0023,
    type: 'metro',
    slug: 'vastra-skogen-1975',
    description: 'Konstverk i Västra skogens tunnelbanestation på den gröna linjen.',
  },
  {
    id: 'riksbanken-1973',
    title: 'Sveriges Riksbank',
    year: 1973,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3290,
    lng: 18.0680,
    type: 'interior',
    description: 'Konstverk i Skandinaviska Bankens Palats, Gustav Adolfs Torg, Stockholm.',
  },
  {
    id: 'medborgarplatsen-1984',
    title: 'Riksbyggen/Göta Ark, Medborgarplatsen',
    year: 1984,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3150,
    lng: 18.0720,
    type: 'interior',
    description: 'Konstverk i Riksbyggens kontorshus vid Medborgarplatsen.',
  },
  {
    id: 'stadsteatern-1970',
    title: 'Stadsteatern Stockholm',
    year: 1970,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3318,
    lng: 18.0644,
    type: 'interior',
    description: 'Konstverk i Stockholms Stadsteaterns interiör, Kulturhuset vid Sergels torg.',
  },
  {
    id: 'nk-ljusgard-1968',
    title: 'NK Ljusgård',
    year: 1968,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3331,
    lng: 18.0689,
    type: 'interior',
    description: 'Konstverk i NK:s ljusgård på Hamngatan.',
  },
  {
    id: 'berns-1991',
    title: 'Berns Ljusgård',
    year: 1991,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3322,
    lng: 18.0739,
    type: 'interior',
    description: 'Konstverk i Berns salongers ljusgård, Berzelii park.',
  },

  // ── Malmö ───────────────────────────────────────────────────
  {
    id: 'gustav-adolfs-torg-2002',
    title: 'Gustav Adolfs torg, fontäner',
    year: 2002,
    city: 'Malmö',
    country: 'Sweden',
    lat: 55.6027,
    lng: 13.0000,
    type: 'exterior',
    slug: 'gustav-adolfs-torg-2002',
    description: 'Fontäner på Gustav Adolfs torg i centrala Malmö.',
  },
  {
    id: 'potatisackern-2001',
    title: 'Potatisåkern — Profilen',
    year: 2001,
    city: 'Malmö',
    country: 'Sweden',
    lat: 55.5952,
    lng: 12.9999,
    type: 'exterior',
    description: 'Profilskulptur i Potatisåkerns park, Malmö.',
  },

  // ── Lund ────────────────────────────────────────────────────
  {
    id: 'skissernas-museum-1988',
    title: 'Skissernas Museum, fasad',
    year: 1988,
    city: 'Lund',
    country: 'Sweden',
    lat: 55.7080,
    lng: 13.1981,
    type: 'exterior',
    description: 'Skulptur på Skissernas Museums fasad i Lund, Finngatan.',
  },

  // ── New York ─────────────────────────────────────────────────
  {
    id: 'nobelmonument-2003',
    title: 'Nobelmonument',
    year: 2003,
    city: 'New York',
    country: 'USA',
    lat: 40.7535,
    lng: -73.9700,
    type: 'exterior',
    slug: 'nobelmonument-new-york-2003',
    description: 'Nobelmonument i New York, vid Dag Hammarskjöld Plaza.',
  },

  // ── Tokyo ────────────────────────────────────────────────────
  {
    id: 'ambassad-tokyo-1990',
    title: 'Sveriges ambassad, entré',
    year: 1990,
    city: 'Tokyo',
    country: 'Japan',
    lat: 35.6646,
    lng: 139.7418,
    type: 'exterior',
    description: 'Entréskulptur vid Sveriges ambassad i Tokyo, Roppongi.',
  },

  // ── Other Swedish cities ──────────────────────────────────────
  {
    id: 'eskilstuna-2002',
    title: 'Eskilstuna rondellen — Profilen',
    year: 2002,
    city: 'Eskilstuna',
    country: 'Sweden',
    lat: 59.3666,
    lng: 16.5077,
    type: 'exterior',
    description: 'Profilskulptur i rondell i centrala Eskilstuna.',
  },
  {
    id: 'baltessspannarparken-2013',
    title: 'Bältesspännarparken',
    year: 2013,
    city: 'Göteborg',
    country: 'Sweden',
    lat: 57.7029,
    lng: 11.9717,
    type: 'exterior',
    slug: 'baltesspaennarparken-2013',
    description: 'Skulptur i Bältesspännarparken, Göteborg.',
  },
  {
    id: 'skövde-1995',
    title: 'Cavallobrunnen, Resecentrum',
    year: 1995,
    city: 'Skövde',
    country: 'Sweden',
    lat: 58.3896,
    lng: 13.8519,
    type: 'exterior',
    description: 'Cavallo-brunn vid Resecentrum i Skövde.',
  },
  {
    id: 'nobel-forum-1993',
    title: 'Nobel Forum',
    year: 1993,
    city: 'Solna',
    country: 'Sweden',
    lat: 59.3427,
    lng: 18.0227,
    type: 'interior',
    description: 'Konstverk i Nobel Forum, Karolinska Institutet, Solna.',
  },
  {
    id: 'pharmacia-1984',
    title: 'Pharmacia entréplats',
    year: 1984,
    city: 'Uppsala',
    country: 'Sweden',
    lat: 59.8419,
    lng: 17.6348,
    type: 'exterior',
    description: 'Konstverk vid Pharmacias entré i Uppsala Science Park.',
  },
  {
    id: 'gu-biblioteket-1985',
    title: 'Göteborgs Universitetsbibliotek',
    year: 1985,
    city: 'Göteborg',
    country: 'Sweden',
    lat: 57.6954,
    lng: 11.9853,
    type: 'interior',
    description: 'Konstverk i Göteborgs Universitetsbibliotek, Humanisten.',
  },

  // ── International ─────────────────────────────────────────────
  {
    id: 'tetra-pak-1984',
    title: 'Tetra Pak',
    year: 1984,
    city: 'Lausanne',
    country: 'Switzerland',
    lat: 46.5071,
    lng: 6.6440,
    type: 'interior',
    description: 'Konstverk i Tetra Paks huvudkontor i Pully, Lausanne.',
  },

  // ── Additional documented locations ───────────────────────────
  {
    id: 'roslagens-sparbank-2004',
    title: 'Roslagens Sparbank',
    year: 2004,
    city: 'Norrtälje',
    country: 'Sweden',
    lat: 59.7580,
    lng: 18.7042,
    type: 'exterior',
    description: 'Skulptur vid Roslagens Sparbank i Norrtälje.',
  },
  {
    id: 'uppsala-stadsbibliotek-1986',
    title: 'Uppsala Stadsbibliotek',
    year: 1986,
    city: 'Uppsala',
    country: 'Sweden',
    lat: 59.8592,
    lng: 17.6375,
    type: 'interior',
    description: 'Konstverk i Uppsala Stadsbibliotek.',
  },
  {
    id: 'vallingby-backe-1966',
    title: 'Vällingby backe',
    year: 1966,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3625,
    lng: 17.8724,
    type: 'exterior',
    description: 'Skulptur vid Vällingby backe i västra Stockholm.',
  },
  {
    id: 'dagens-nyheter-1965',
    title: 'Bronsgaller, Dagens Nyheter',
    year: 1965,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3280,
    lng: 18.0148,
    type: 'exterior',
    description: 'Bronsgaller vid Dagens Nyheters redaktion, Marieberg.',
  },
  {
    id: 'kristianstad-1989',
    title: 'Tivoliparken',
    year: 1989,
    city: 'Kristianstad',
    country: 'Sweden',
    lat: 56.0294,
    lng: 14.1567,
    type: 'exterior',
    description: 'Skulpturgrupp i Tivoliparken, Kristianstad.',
  },
  {
    id: 'trollhattan-1989',
    title: 'Norra Älvsborgs Länssjukhus',
    year: 1989,
    city: 'Trollhättan',
    country: 'Sweden',
    lat: 58.2837,
    lng: 12.2881,
    type: 'exterior',
    description: 'Skulptur vid Norra Älvsborgs Länssjukhus.',
  },
  {
    id: 'kalmar-1990',
    title: 'Kvarteret Baronen',
    year: 1990,
    city: 'Kalmar',
    country: 'Sweden',
    lat: 56.6634,
    lng: 16.3568,
    type: 'interior',
    description: 'Skulptur i Baronen köpcentrum, Kalmar.',
  },
  {
    id: 'aneby-1988',
    title: 'Aneby Servicehus',
    year: 1988,
    city: 'Aneby',
    country: 'Sweden',
    lat: 57.8386,
    lng: 14.8071,
    type: 'interior',
    description: 'Konstverk i Aneby Servicehus.',
  },
  {
    id: 'norrkoping-1986',
    title: 'Länssjukhuset Vrinnevi, innergård',
    year: 1986,
    city: 'Norrköping',
    country: 'Sweden',
    lat: 58.5831,
    lng: 16.1981,
    type: 'exterior',
    description: 'Skulptur i innergården vid Vrinnevisjukhuset, Norrköping.',
  },
  {
    id: 'lindholmsallen-goteborg',
    title: 'Lindholmsallén',
    year: 1990,
    city: 'Göteborg',
    country: 'Sweden',
    lat: 57.7049,
    lng: 11.9437,
    type: 'exterior',
    description: 'Skulptur längs Lindholmsallén, Göteborg.',
  },
  {
    id: 'farsta-1967',
    title: 'Farsta Sjukhus',
    year: 1967,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.2435,
    lng: 18.0912,
    type: 'exterior',
    description: 'Skulptur vid Farsta Sjukhus.',
  },
  {
    id: 'haninge-1970',
    title: 'Västerhaninge Bibliotek, Haninge Kulturhus',
    year: 1970,
    city: 'Handen',
    country: 'Sweden',
    lat: 59.1548,
    lng: 18.1432,
    type: 'interior',
    description: 'Skulptur i Haninge Kulturhus.',
  },
  {
    id: 'motala-1978',
    title: 'Motala Folkets Hus',
    year: 1978,
    city: 'Motala',
    country: 'Sweden',
    lat: 58.5367,
    lng: 15.0361,
    type: 'interior',
    description: 'Konstverk i Motala Folkets Hus.',
  },
  {
    id: 'paris-ccs-1980',
    title: 'Centre Culturel Suédois',
    year: 1980,
    city: 'Paris',
    country: 'France',
    lat: 48.8566,
    lng: 2.3522,
    type: 'exterior',
    description: 'Skulptur vid Centre Culturel Suédois, Paris.',
  },
]
