export interface SculptureLocation {
  id: string
  title: string
  year: number
  city: string
  country: string
  lat: number
  lng: number
  type: 'exterior' | 'interior' | 'metro'
  slug?: string
  description?: string
}

// Coordinates verified against old site map (MapPress/Google Maps data, scraped 2026-05-04)
export const SCULPTURE_LOCATIONS: SculptureLocation[] = [
  // ── Stockholm exteriors ─────────────────────────────────────
  {
    id: 'blasieholmstorg-1989',
    title: 'Blasieholmstorg — Hästar i brons',
    year: 1989,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3310,
    lng: 18.0745,
    type: 'exterior',
    slug: 'blasieholmstorg-stockholm-1989',
    description: 'Två grönpatinerade bronshästar inspirerade av San Marcoshästarna i Venedig.',
  },
  {
    id: 'sergels-torg-1998',
    title: 'Sergels torg — Sergel monumentet',
    year: 1998,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3328,
    lng: 18.0658,
    type: 'exterior',
    description: 'Monument på Sergels torg, centrala Stockholm.',
    slug: 'sergels-torg-sergel-monumentet-stockholm-1998',
  },
  {
    id: 'kungliga-biblioteket-1998',
    title: 'Kungliga Biblioteket',
    year: 1998,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3381,
    lng: 18.0718,
    type: 'exterior',
    description: 'Skulptur vid Kungliga Bibliotekets fasad, Humlegården.',
    slug: 'kungl-biblioteket-stockholm-1998',
  },
  {
    id: 'synagogan-1998',
    title: 'Synagoga — Förintelsemonumentet',
    year: 1998,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3308,
    lng: 18.0735,
    type: 'exterior',
    description: 'Minnesmärke för Förintelsen vid Stockholms synagoga, Wahrendorffsgatan 3.',
    slug: 'synagoga-forintelsemonumentet-stockholm-1998',
  },
  {
    id: 'frescati-1987',
    title: 'Stockholms Universitet Campus',
    year: 1987,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3653,
    lng: 18.0553,
    type: 'exterior',
    slug: 'stockholms-universitet-campus-1987-91',
    description: 'Skulpturer på Stockholms Universitets campus i Frescati.',
  },
  {
    id: 'sas-huvudkontor-1988',
    title: 'SAS Huvudkontor, Frösundavik',
    year: 1988,
    city: 'Solna',
    country: 'Sweden',
    lat: 59.3709,
    lng: 18.0234,
    type: 'exterior',
    description: 'Utomhusskulptur vid SAS huvudkontor i Frösundavik, Solna.',
    slug: 'sas-huvudkontor-frosundavik-stockholm-1988',
  },
  {
    id: 'haga-norra-1993',
    title: 'Haga Norra gångbro',
    year: 1993,
    city: 'Solna',
    country: 'Sweden',
    lat: 59.3633,
    lng: 18.0253,
    type: 'exterior',
    description: 'Skulptur på gångbro vid Haga Norra, Solna.',
    slug: 'haga-norra-gangbro-stockholm-1993',
  },
  {
    id: 'seb-banken-1992',
    title: 'SEB Banken Huvudkontor',
    year: 1992,
    city: 'Sundbyberg',
    country: 'Sweden',
    lat: 59.3809,
    lng: 17.9370,
    type: 'exterior',
    description: 'Skulptur vid SEB:s huvudkontor i Rissne, Rissneleden 110, Sundbyberg.',
    slug: 'seb-banken-huvudkontor-rissne-1992',
  },
  {
    id: 'kungstradgarden-1997',
    title: 'Kungsträdgården, norra delen',
    year: 1997,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3321,
    lng: 18.0708,
    type: 'exterior',
    description: 'Skulptur i Kungsträdgårdens norra del.',
    slug: 'kungstradgarden-norra-delen-1997-98',
  },
  {
    id: 'fersenska-palatset-1975',
    title: 'Fersenska Palatset, Handelsbanken',
    year: 1975,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3305,
    lng: 18.0747,
    type: 'exterior',
    description: 'Skulptur i Fersenska Palatsets innergård, Blasieholmstorg.',
    slug: 'fersenska-palatset-handelsbanken-stockholm-1975',
  },
  {
    id: 'garnisonen-1972',
    title: 'Garnisonen',
    year: 1972,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3362,
    lng: 18.0952,
    type: 'exterior',
    description: 'Skulptur vid Garnisonen på Östermalm, Karlavägen.',
    slug: 'garnisonen-stockholm-1972',
  },
  {
    id: 'kungstradgarden-norra-1997',
    title: 'Grubbens Trappor',
    year: 2000,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3350,
    lng: 18.0418,
    type: 'exterior',
    slug: 'st-erik-grubbens-trappa-kungsholmen-stockholm-2000',
    description: 'Skulptur vid Grubbens Trappor, S:t Eriksgatan, Kungsholmen.',
  },
  {
    id: 'konstakademien-fredsgatan-12',
    title: 'Konstakademiens trappa, Fredsgatan 12',
    year: 1975,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3318,
    lng: 18.0620,
    type: 'exterior',
    description: 'Skulptur vid trappan till Kungl. Akademien för de fria konsterna, Fredsgatan 12, Stockholm.',
  },
  {
    id: 'grev-magnigatan-10',
    title: 'Grev Magnigatan 10 — skulpturer på innergård',
    year: 2000,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3358,
    lng: 18.0795,
    type: 'exterior',
    slug: 'grev-magnigatan-10',
    description: 'Två skulpturer placerade på innergården till Grev Magnigatan 10, Östermalm.',
  },
  {
    id: 'ringvagen-1989',
    title: 'Lindros gård / Kvarteret Svärdet',
    year: 1988,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3099,
    lng: 18.0617,
    type: 'exterior',
    slug: 'kvarteret-svardet-stockholm1989',
    description: 'Tegelmonolit med tre klot i triangelformation på innergården, Ringvägen–Maria Bangata, Södermalm.',
  },
  {
    id: 'vallingby-backe-1966',
    title: 'Vällingby backe',
    year: 1966,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3626,
    lng: 17.8707,
    type: 'exterior',
    description: 'Skulptur vid Vällingby backe (vid sidan om biografen Fontänen).',
    slug: 'vallingby-backe-1966-67',
  },
  {
    id: 'dagens-nyheter-1965',
    title: 'Bronsgaller, Dagens Nyheter',
    year: 1965,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3279,
    lng: 18.0154,
    type: 'exterior',
    description: 'Bronsgaller vid Dagens Nyheters redaktion, Gjörwellsgatan 30, Marieberg.',
    slug: 'bronsgaller-dagens-nyheter-stockholm-1965',
  },

  // ── Stockholm interiors / tunnelbana ────────────────────────
  {
    id: 'vastra-skogen-1975',
    title: 'Västra skogen T-banestation',
    year: 1975,
    city: 'Solna',
    country: 'Sweden',
    lat: 59.3475,
    lng: 18.0040,
    type: 'metro',
    slug: 'vastra-skogen-t-banestation-1975-1985',
    description: 'Konstverk i Västra skogens tunnelbanestation på den gröna linjen.',
  },
  {
    id: 'riksbanken-1973',
    title: 'Sveriges Riksbank',
    year: 1973,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3290,
    lng: 18.0680,
    type: 'interior',
    description: 'Konstverk i Riksbanken, Gustav Adolfs Torg, Stockholm.',
    slug: 'sveriges-riksbank-stockholm-1973',
  },
  {
    id: 'medborgarplatsen-1984',
    title: 'Riksbyggen/Göta Ark, Medborgarplatsen',
    year: 1984,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3153,
    lng: 18.0709,
    type: 'interior',
    description: 'Konstverk i Riksbyggens kontorshus vid Medborgarplatsen.',
    slug: 'riksbyggen-gota-ark-medborgarplatsen-stockholm-1984',
  },
  {
    id: 'stadsteatern-1970',
    title: 'Stadsteatern Stockholm',
    year: 1970,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3318,
    lng: 18.0648,
    type: 'interior',
    description: 'Konstverk i Stockholms Stadsteaterns förbindelsegång, Kulturhuset vid Sergels torg.',
    slug: 'stadsteatern-stockholm-1970',
  },
  {
    id: 'nk-ljusgard-1968',
    title: 'NK Ljusgård',
    year: 1968,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3333,
    lng: 18.0686,
    type: 'interior',
    description: 'Konstverk i NK:s ljusgård på Hamngatan.',
    slug: 'nk-ljusgard-1968',
  },
  {
    id: 'berns-1991',
    title: 'Berns Ljusgård',
    year: 1991,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3321,
    lng: 18.0738,
    type: 'interior',
    description: 'Konstverk i Berns salongers ljusgård, Berzelii park.',
    slug: 'berns-ljusgard-1991',
  },
  {
    id: 'medelhavsmuseet-1982',
    title: 'Medelhavsmuseet',
    year: 1982,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3294,
    lng: 18.0674,
    type: 'interior',
    description: 'Konstverk i Medelhavsmuseet, Fredsgatan 2, Stockholm.',
    slug: 'medelhavsmuseet-stockholm-1982-utstallning-ar-numera-utbytt',
  },

  // ── Solna ──────────────────────────────────────────────────
  {
    id: 'nobel-forum-1993',
    title: 'Nobel Forum',
    year: 1993,
    city: 'Solna',
    country: 'Sweden',
    lat: 59.3427,
    lng: 18.0227,
    type: 'interior',
    description: 'Konstverk i Nobel Forum, Karolinska Institutet, Solna.',
    slug: 'nobel-forum',
  },
  {
    id: 'norra-begravningsplatsen',
    title: 'Norra Begravningsplatsen',
    year: 1985,
    city: 'Solna',
    country: 'Sweden',
    lat: 59.3556,
    lng: 18.0279,
    type: 'exterior',
    description: 'Skulptur vid Norra Begravningsplatsen, Solna.',
  },

  // ── Malmö ───────────────────────────────────────────────────
  {
    id: 'gustav-adolfs-torg-2002',
    title: 'Gustav Adolfs torg, fontäner',
    year: 2002,
    city: 'Malmö',
    country: 'Sweden',
    lat: 55.6050,
    lng: 13.0022,
    type: 'exterior',
    slug: 'gustav-adolfs-torg-malmo-2002',
    description: 'Fontäner på Gustav Adolfs torg i centrala Malmö.',
  },
  {
    id: 'potatisackern-2001',
    title: 'Potatisåkern — Profilen',
    year: 2001,
    city: 'Malmö',
    country: 'Sweden',
    lat: 55.5973,
    lng: 12.9571,
    type: 'exterior',
    description: 'Profilskulptur i Potatisåkerns park, Limhamnsvägen × Köpenhamnsvägen, Malmö.',
    slug: 'potatisakern-bostadsomrade-malmo-2001',
  },

  // ── Lund ────────────────────────────────────────────────────
  {
    id: 'skissernas-museum-1988',
    title: 'Skissernas Museum, fasad',
    year: 1988,
    city: 'Lund',
    country: 'Sweden',
    lat: 55.7081,
    lng: 13.1982,
    type: 'exterior',
    description: 'Skulptur på Skissernas Museums fasad i Lund, Finngatan 2.',
    slug: 'skissernas-museum-fasad-1988',
  },

  // ── Göteborg ────────────────────────────────────────────────
  {
    id: 'baltesspaennarparken-2013',
    title: 'Bältesspännarparken',
    year: 2013,
    city: 'Göteborg',
    country: 'Sweden',
    lat: 57.6988,
    lng: 11.9641,
    type: 'exterior',
    slug: 'baltesspannarparken-goteborg-2013',
    description: 'Skulptur i Bältesspännarparken, Göteborg.',
  },
  {
    id: 'gu-biblioteket-1985',
    title: 'Göteborgs Universitetsbibliotek',
    year: 1985,
    city: 'Göteborg',
    country: 'Sweden',
    lat: 57.6914,
    lng: 11.9561,
    type: 'interior',
    description: 'Konstverk i Göteborgs Universitetsbibliotek, Seminariegatan 1D.',
    slug: 'goteborgs-universitetsbibliotek-1985',
  },
  {
    id: 'lindholmsallen-goteborg',
    title: 'Lindholmsallén',
    year: 1990,
    city: 'Göteborg',
    country: 'Sweden',
    lat: 57.7114,
    lng: 11.9432,
    type: 'exterior',
    description: 'Skulptur längs Lindholmsallén, Göteborg.',
    slug: 'lindholmsallen-regnbagsgatan-goteborg',
  },

  // ── Uppsala ─────────────────────────────────────────────────
  {
    id: 'pharmacia-1984',
    title: 'Pharmacia entréplats',
    year: 1984,
    city: 'Uppsala',
    country: 'Sweden',
    lat: 59.8533,
    lng: 17.6971,
    type: 'exterior',
    description: 'Konstverk vid Pharmacias entré i Fyrislund, Uppsala.',
    slug: 'pharmacia-entreplats-uppsala-1984-85',
  },
  {
    id: 'uppsala-stadsbibliotek-1986',
    title: 'Uppsala Stadsbibliotek',
    year: 1986,
    city: 'Uppsala',
    country: 'Sweden',
    lat: 59.8606,
    lng: 17.6353,
    type: 'interior',
    description: 'Konstverk i Uppsala Stadsbibliotek, Svartbäcksgatan 17.',
    slug: 'uppsala-stadsbibliotek-1986',
  },

  // ── Eskilstuna ──────────────────────────────────────────────
  {
    id: 'eskilstuna-2002',
    title: 'Eskilstuna rondellen — Profilen',
    year: 2002,
    city: 'Eskilstuna',
    country: 'Sweden',
    lat: 59.3728,
    lng: 16.5153,
    type: 'exterior',
    description: 'Profilskulptur i rondellen Hamngatan–Nybrogatan, Eskilstuna.',
    slug: 'eskilstuna-rondellen-profilen-2002',
  },
  {
    id: 'arbyparken-1973',
    title: 'Lekplats Årbysområdet',
    year: 1973,
    city: 'Eskilstuna',
    country: 'Sweden',
    lat: 59.3824,
    lng: 16.5176,
    type: 'exterior',
    description: 'Lekplatsskulptur i Årbysområdet, Eskilstuna.',
    slug: 'lekplats-arby-omradet-eskilstuna-1973',
  },

  // ── Skövde ──────────────────────────────────────────────────
  {
    id: 'skövde-1995',
    title: 'Cavallobrunnen, Resecentrum',
    year: 1995,
    city: 'Skövde',
    country: 'Sweden',
    lat: 58.3894,
    lng: 13.8514,
    type: 'exterior',
    description: 'Cavallo-brunn vid Resecentrum i Skövde, Stationsgatan.',
    slug: 'cavallobrunnen-resecentrum-skovde-1995-96',
  },

  // ── Norrtälje ───────────────────────────────────────────────
  {
    id: 'norrtälje-stadsbibliotek-2006',
    title: 'Norrtälje Stadsbibliotek',
    year: 2006,
    city: 'Norrtälje',
    country: 'Sweden',
    lat: 59.7594,
    lng: 18.7027,
    type: 'interior',
    description: 'Konstverk i Norrtälje Stadsbibliotek / Roslagens Sparbank, Billborgsgatan 3.',
    slug: 'roslagens-sparbank-norrtalje-2004',
  },

  // ── Other Swedish cities ─────────────────────────────────────
  {
    id: 'kristianstad-1989',
    title: 'Tivoliparken',
    year: 1989,
    city: 'Kristianstad',
    country: 'Sweden',
    lat: 56.0281,
    lng: 14.1540,
    type: 'exterior',
    description: 'Skulpturgrupp i Tivoliparken med sortimentsträdgården, Kristianstad.',
    slug: 'kristianstad-tivoliparken-1989',
  },
  {
    id: 'trollhattan-1989',
    title: 'Norra Älvsborgs Länssjukhus',
    year: 1989,
    city: 'Trollhättan',
    country: 'Sweden',
    lat: 58.3173,
    lng: 12.2664,
    type: 'exterior',
    description: 'Skulptur vid Norra Älvsborgs Länssjukhus, Lärketorpsvägen, Trollhättan.',
    slug: 'norra-alvsborgs-lanssjukhus-trollhattan-1989-91',
  },
  {
    id: 'kalmar-1990',
    title: 'Kvarteret Baronen',
    year: 1990,
    city: 'Kalmar',
    country: 'Sweden',
    lat: 56.6611,
    lng: 16.3651,
    type: 'exterior',
    description: 'Skulptur i Kvarteret Baronen, Skeppsbrogatan 12, Kalmar.',
    slug: 'kvarteret-baronen-kalmar-1990',
  },
  {
    id: 'norrkoping-1986',
    title: 'Länssjukhuset Vrinnevi, innergård',
    year: 1986,
    city: 'Norrköping',
    country: 'Sweden',
    lat: 58.5637,
    lng: 16.1791,
    type: 'exterior',
    description: 'Skulptur i innergården vid Vrinnevisjukhuset, Gamla Övägen 25, Norrköping.',
    slug: 'lanssjukhuset-vrinnevi-innergard-norrkoping-1986',
  },
  {
    id: 'haninge-1970',
    title: 'Haninge Kulturhus',
    year: 1970,
    city: 'Handen',
    country: 'Sweden',
    lat: 59.1676,
    lng: 18.1399,
    type: 'interior',
    description: 'Skulptur i Haninge Kulturhus, Poseidons Torg 8, Handen.',
    slug: 'vasterhaninge-bibliotek-haninge-kulturhus-1970',
  },
  {
    id: 'vadsbo-museum-1962',
    title: 'Vadsbo Museum',
    year: 1962,
    city: 'Mariestad',
    country: 'Sweden',
    lat: 58.7095,
    lng: 13.8235,
    type: 'exterior',
    description: 'Konstverk vid Vadsbo Museum, Marieholmsbron 3, Mariestad.',
  },
  {
    id: 'korsbarsgarden-2010',
    title: 'Körsbärsgården, Gotland',
    year: 2010,
    city: 'Gotland',
    country: 'Sweden',
    lat: 56.9327,
    lng: 18.1700,
    type: 'exterior',
    description: 'Skulptur vid Körsbärsgården, Sundre, Gotland.',
  },
  {
    id: 'visby-lasarett',
    title: 'Visby Lasarett',
    year: 1980,
    city: 'Visby',
    country: 'Sweden',
    lat: 57.6496,
    lng: 18.3009,
    type: 'exterior',
    description: 'Skulptur vid Visby Lasarett, S:t Göransgatan 5, Visby.',
    slug: 'visby-lasarett-urna',
  },

  // ── International ─────────────────────────────────────────────
  {
    id: 'nobelmonument-2003',
    title: 'Nobelmonument',
    year: 2003,
    city: 'New York',
    country: 'USA',
    lat: 40.7824,
    lng: -73.9746,
    type: 'exterior',
    slug: 'nobelmonument-new-york-2003',
    description: 'Nobelmonument vid Theodore Roosevelt Park, 200 Central Park West, New York.',
  },
  {
    id: 'ambassad-tokyo-1990',
    title: 'Sveriges ambassad, entré',
    year: 1990,
    city: 'Tokyo',
    country: 'Japan',
    lat: 35.6647,
    lng: 139.7418,
    type: 'exterior',
    description: 'Entréskulptur vid Sveriges ambassad, 1-10-3 Roppongi, Minato-ku, Tokyo.',
    slug: 'sveriges-ambassaden-entre-tokyo-1990-91',
  },
  {
    id: 'tetra-pak-1984',
    title: 'Tetra Pak',
    year: 1984,
    city: 'Lausanne',
    country: 'Switzerland',
    lat: 46.5071,
    lng: 6.6440,
    type: 'interior',
    description: 'Konstverk i Tetra Paks huvudkontor, Avenue Général-Guisan 70, Pully/Lausanne.',
    slug: 'tetra-pak-lausanne-schweiz-1984-85',
  },
  {
    id: 'paris-ccs-1980',
    title: 'Centre Culturel Suédois',
    year: 1980,
    city: 'Paris',
    country: 'France',
    lat: 48.8581,
    lng: 2.3623,
    type: 'exterior',
    description: 'Skulptur vid Institut Suédois, 11 Rue Payenne, Paris.',
    slug: 'sans-titre-centre-culturel-suedois-ccs-paris-1980',
  },


  // ── Additional works (added by migration script) ─────────────
  {
    id: 'aterinvigning-av-ulriksdalsbron',
    title: 'Återinvigning Haga Norra gångbro 2015',
    year: 2015,
    city: 'Solna',
    country: 'Sweden',
    lat: 59.3633,
    lng: 18.0253,
    type: 'exterior',
    slug: 'aterinvigning-av-ulriksdalsbron',
    description: 'Återinvigning av Haga Norra gångbro med rekonstruerade bronssfärer och urna.',
  },
  {
    id: 'st-erik-grubbens-trappa',
    title: 'S:t Erik, Grubbens trappa',
    year: 2000,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.335,
    lng: 18.0418,
    type: 'exterior',
    slug: 'st-erik-grubbens-trappa-kungsholmen-stockholm-2000',
    description: 'Bronsprofilhuvuden längs trappan på f.d. S:t Eriks sjukhustomt.',
  },
  {
    id: 'farsta-sjukhus-1967',
    title: 'Farsta sjukhus — Kepler',
    year: 1967,
    city: 'Farsta',
    country: 'Sweden',
    lat: 59.2405,
    lng: 18.0977,
    type: 'exterior',
    slug: 'farsta-sjukhus-1967',
    description: 'Balanserad skulptur "Kepler" utanför Farsta sjukhus.',
  },
  {
    id: 'lugnet-park',
    title: 'Lugnet park',
    year: 1980,
    city: 'Falun',
    country: 'Sweden',
    lat: 60.5931,
    lng: 15.6319,
    type: 'exterior',
    slug: 'lugnet-park-projektforslag-1979-80',
    description: 'Projektförslag för parkgestaltning i Lugnet.',
  },
  {
    id: 'celsingarkivet',
    title: 'Celsingarkivet',
    year: 1980,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.322,
    lng: 18.0694,
    type: 'interior',
    slug: 'celsingarkivet-kornhamnstorg-49-3tr',
    description: 'Arkiv med ritningar och modeller från Peter Celsings produktion.',
  },
  {
    id: 'drivved-1987',
    title: 'Scenografi: Drivved',
    year: 1987,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3198,
    lng: 18.072,
    type: 'interior',
    slug: 'drivved-fragment-ur-tidigare-koreografier-av-och-med-margareta-asberg',
    description: 'Scenografi för Margaretha Åsbergs koreografiska verk på Moderna Dansteatern.',
  },
  {
    id: 'sand-1974',
    title: 'Scenografi: Sand',
    year: 1974,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3198,
    lng: 18.0715,
    type: 'interior',
    slug: 'sand-10-rorelsedikter-med-koreograf-margareta-asberg-1974',
    description: 'Scenografi till "Sand" av Margaretha Åsberg på Fylkingen.',
  },
  {
    id: 'falska-fortroenden-1982',
    title: 'Scenografi: Falska förtroenden',
    year: 1982,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3318,
    lng: 18.0648,
    type: 'interior',
    slug: 'scenografi-falska-fortroenden-av-marivaux-stockholms-stadsteater-1982',
    description: 'Scenografi till Marivaux pjäs på Stockholms Stadsteater.',
  },
  {
    id: 'motala-folkets-hus',
    title: 'Motala Folkets Hus',
    year: 1978,
    city: 'Motala',
    country: 'Sweden',
    lat: 58.5381,
    lng: 15.0428,
    type: 'interior',
    slug: 'motala-folkets-hus-motala-i-samarbete-med-ulrik-samuelson-1978',
    description: 'Tegelvägginstallationer i Motala Folkets Hus.',
  },
  {
    id: 'norrlands-nationshus-1972',
    title: 'Norrlands Nationshus — takmålning',
    year: 1972,
    city: 'Uppsala',
    country: 'Sweden',
    lat: 59.8591,
    lng: 17.6372,
    type: 'interior',
    slug: 'takmalning-norrlands-nationshus-uppsala-i-samarbete-med-ulrik-samuelson-1972',
    description: 'Stor takmålning av målade glasrutor i Norrlands Nationshus.',
  },
  {
    id: 'tegelvagg-boras-1957',
    title: 'Tegelvägg, Gustav Adolfs församlingshem',
    year: 1957,
    city: 'Borås',
    country: 'Sweden',
    lat: 57.721,
    lng: 12.9407,
    type: 'interior',
    slug: 'tegelvagg-gustav-adolfs-forsamlingshem-boras-med-olle-adrin-1957',
    description: 'Inre tegelvägg i Gustav Adolfs församlingshem, ett av Lindbloms tidigaste offentliga verk.',
  },
  {
    id: 'krucifix-smogen',
    title: 'Krucifix — frikyrka på Smögen',
    year: 1955,
    city: 'Smögen',
    country: 'Sweden',
    lat: 58.3583,
    lng: 11.2268,
    type: 'interior',
    slug: 'krucefix-frikyrka-pa-smogen',
    description: 'Tidigt krucifix för en frikyrka på Smögen.',
  },
  {
    id: 'kulturhuset-stadsteatern-passage',
    title: 'Förbindelsegång Kulturhuset–Stadsteatern',
    year: 1989,
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3318,
    lng: 18.0648,
    type: 'interior',
    slug: 'forbindelsegang-mellan-kulturhuset-och-stadsteaterns-stora-scen-stockholm-1989-92',
    description: 'Passage som förbinder Kulturhuset med Stadsteaterns Stora Scen.',
  },
]
